name: Bump version
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Bump version and push tag
      uses: TriPSs/conventional-changelog-action@master
      with:
        git-message: 'Test message'
        tag-prefix: ''
        output-file: 'CHANGELOG.md'
